# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'baseapp_mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for baseapp_mobile

  target 'baseapp_mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'baseapp_mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'baseapp_mobile-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for baseapp_mobile-tvOS

  target 'baseapp_mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
